apiVersion: v1
kind: Service
metadata:
  name: nginxtls
  labels:
    run: nginxtls
spec:
  selector:
    run: nginxtls
  ports:
  - name: https
    protocol: TCP
    port: 8080
    targetPort: 8080
  #type: ClusterIP
