apiVersion: v1
kind: Service
metadata:
  name: nginxqat
  labels:
    run: nginxqat
spec:
  selector:
    run: nginxqat
  ports:
  - name: https
    protocol: TCP
    port: 8080
    targetPort: 8080
  #type: ClusterIP
