apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user root;
    worker_processes 128;
    worker_priority 0;
    worker_rlimit_nofile 1000000;
    load_module modules/ngx_ssl_engine_qat_module.so;

    events {
       use epoll;
       worker_connections 8192;
       multi_accept on;
       accept_mutex on;
     }

    ssl_engine {
        use_engine qatengine;
        default_algorithms ALL;
        qat_engine {
               qat_offload_mode async;
               qat_notify_mode poll;
               qat_poll_mode heuristic;
               #qat_shutting_down_release off;
               #qat_external_poll_interval 1;

        }

    }

    http {
      include /usr/share/nginx/conf/mime.types;
      default_type  application/octet-stream;
      limit_conn_zone $server_name zone=perserver:3072000;
      sendfile on;
      access_log off;

      server {
         #set $server_ip 127.0.0.1;
         listen 8080 asynch reuseport backlog=131072 so_keepalive=on rcvbuf=65536 sndbuf=65536;
         #listen 8080 asynch reuseport so_keepalive=on;
         server_name  localhost;
         sendfile on;
         sendfile_max_chunk 524288;
         keepalive_timeout 0s;
         tcp_nopush on;
         tcp_nodelay on;
         #keepalive_requests 100000;
         #keepalive_requests 100000;
         ssl_verify_client off;
         ssl_session_tickets off;
         limit_conn perserver 65500;
         ssl_buffer_size 65536;
         access_log off;
         ssl_asynch on;
         ssl_session_timeout 300s;
         ssl_protocols TLSv1.3;
         #ssl_ciphers  ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:AES128-SHA:AES256-SHA:AES128-GCM-SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256;
         #ssl_ciphers AES128-SHA;
         ssl_ciphers ALL;
         ssl_prefer_server_ciphers on;
         ssl_certificate      /keys/server.crt;
         ssl_certificate_key  /keys/server.key;

         location / {

            #root /usr/share/nginx/html;
            root html;
            index index.html index.htm;

         }

       }

    }
