apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxqat
spec:
  selector:
    matchLabels:
      run: nginxqat
  replicas: 1
  template:
    metadata:
      labels:
        run: nginxqat
    spec:
      containers:
      - name: nginxqat
        #image: harbor.wpax.intel.com/dev/openresty-hw-qat
        image: harbor.wpax.intel.com/dev/manjeets/async-qat-nginx-standalone
        imagePullPolicy: Always
        #command: [ "/bin/bash", "-c", "--" ]
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        command: [ "/bin/bash", "-c", "export QAT_POLICY=1 && nginx -c /etc/nginx/nginx.conf -g 'daemon off;'" ]
          #command: [ "/bin/bash", "-c", "--" ]
          #args: [ "while true; do sleep 300000; done;" ]
        securityContext:
          privileged: True
          capabilities:
            add:
              ["IPC_LOCK"]
        resources:
          requests:
            qat.intel.com/asym: 128
          limits:
            qat.intel.com/asym: 128
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      nodeSelector:
         kubernetes.io/hostname: fmx040
      hostname: nginxqat
      restartPolicy: Always
