apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user root;
    worker_processes 128;
    worker_priority 0;
    worker_rlimit_nofile 1000000;
    
    events {
       use epoll;
       worker_connections 8192;
       multi_accept on;
       accept_mutex on;
    }
    http {
        include       mime.types;
        default_type  application/octet-stream;
        limit_conn_zone $server_name zone=perserver:3072000;
        sendfile on;
        access_log off;
        
        server {
            listen 8080 ssl reuseport backlog=131072 so_keepalive=off  rcvbuf=65536 sndbuf=65536;
            sendfile on;
            sendfile_max_chunk 524288;
            keepalive_timeout 0s;
            tcp_nopush on;
            tcp_nodelay on;
            ssl_verify_client off;
            ssl_session_tickets   off;
            access_log  off;
            limit_conn perserver 65500;
            lingering_close off;
            lingering_time 1;
            server_name localhost;

            ssl_certificate      /keys/server.crt;
            ssl_certificate_key  /keys/server.key;

            ssl_session_timeout  300s;
            ssl_ecdh_curve X25519;

            ssl_protocols  TLSv1.3;
            ssl_buffer_size 65536;
            ssl_ciphers  ALL;
            ssl_prefer_server_ciphers   on;

            location / {
               root   html;
               index  index.html index.htm;
            }
        }
   }
