version: '3'
services:
  myapp:
    image: harbor.wpax.intel.com/dev/manjeets/async-qat-nginx-standalone 
    command: [ "/bin/bash", "-c", "export QAT_POLICY=1 && nginx -c /etc/nginx/nginx.conf -g 'daemon off;'" ]
    ports:
      - "8080:8181"
